import Head from "next/head";
import React, { ReactNode } from "react";
import Footer from "./Footer";

export interface LayoutProps extends React.ComponentPropsWithoutRef<"div"> {}

// type LayoutProps = {
//   children: ReactNode;
// };

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="My Portfolio" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen flex flex-col">
        <main>{children}</main>
        <div className="m-auto"></div>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
