import Head from "next/head";
import React from "react";
import { Caveat } from "@next/font/google";

const caveat = Caveat({
  variable: "--caveat-font",
  subsets: ["cyrillic", "latin"],
});

export interface LayoutProps extends React.ComponentPropsWithoutRef<"div"> {}

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="My Portfolio" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <main
          className={`${caveat.variable} flex flex-col overflow-x-hidden scroll-smooth `}
        >
          {children}
        </main>
      </div>
    </>
  );
};

export default Layout;
